# -*- Mode:cmake; Coding:us-ascii-unix; fill-column:158 -*-
#########################################################################################################################################################.H.S.##
##
# @file      CMakeLists.txt
# @author    Mitch Richling http://www.mitchr.me/
# @date      2026-05-02
# @version   VERSION
# @brief     @EOL
# @keywords  
# @std       cmake
# @see       
# @copyright 
#  @parblock
#  Copyright (c) 2026, Mitchell Jay Richling <http://www.mitchr.me/> All rights reserved.
#  
#  Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
#  
#  1. Redistributions of source code must retain the above copyright notice, this list of conditions, and the following disclaimer.
#  
#  2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions, and the following disclaimer in the documentation
#     and/or other materials provided with the distribution.
#  
#  3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software
#     without specific prior written permission.
#  
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
#  OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
#  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
#  DAMAGE.
#  @endparblock
# @todo      @EOL@EOL
# @warning   @EOL@EOL
# @bug       @EOL@EOL
# @filedetails
#
#  This CMakeLists.txt file is designed to be a drop-in replacement for the one generated by STM32CubeMX.  I have had great success with it; however, my only
#  use a handfull of STM32 devices and my use cases are very simplistic.
#
#########################################################################################################################################################.H.E.##

#---------------------------------------------------------------------------------------------------------------------------------------------------------------
cmake_minimum_required(VERSION 3.22)

#---------------------------------------------------------------------------------------------------------------------------------------------------------------
# Setup compiler settings
set(CMAKE_C_STANDARD 11)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_C_EXTENSIONS ON)

#---------------------------------------------------------------------------------------------------------------------------------------------------------------
message(STATUS "CMAKE_SOURCE_DIR: ${CMAKE_SOURCE_DIR}")

#---------------------------------------------------------------------------------------------------------------------------------------------------------------
# Check the build type.  Make sure it is one of the two CubeMX creates.
if(NOT CMAKE_BUILD_TYPE)
  message(FATAL_ERROR "Build type (CMAKE_BUILD_TYPE) not set.  Use --prefix argument to set value")
else()
  if(NOT((CMAKE_BUILD_TYPE STREQUAL "Debug") OR (CMAKE_BUILD_TYPE STREQUAL "Release")))
    message(FATAL_ERROR "Build type (${CMAKE_BUILD_TYPE}) not supported!")
  endif()
endif()
message(STATUS "CMAKE_BUILD_TYPE: " ${CMAKE_BUILD_TYPE})

#---------------------------------------------------------------------------------------------------------------------------------------------------------------
# Set the project name
# By CubeMX convention this is also the name of the project directory and final firmware ELF file.  
get_filename_component(CMAKE_PROJECT_NAME ${CMAKE_SOURCE_DIR} NAME)
message(STATUS "CMAKE_PROJECT_NAME: ${CMAKE_PROJECT_NAME}")

# Enable compile command to ease indexing with e.g. clangd
set(CMAKE_EXPORT_COMPILE_COMMANDS TRUE)

#---------------------------------------------------------------------------------------------------------------------------------------------------------------
# Define Project
project(${CMAKE_PROJECT_NAME})

# Enable CMake support for C++, C, & ASM -- not ASM must always be last on this list.
enable_language(CXX C ASM)

#---------------------------------------------------------------------------------------------------------------------------------------------------------------
# Override CMAKE_BUILD_TYPE specific CMAKE_C & CMAKE_CXX flags from the toolchain file.
set(CMAKE_C_FLAGS_DEBUG     "-Og    -g3")
set(CMAKE_C_FLAGS_RELEASE   "-Ofast -g0")
set(CMAKE_CXX_FLAGS_DEBUG   "-Og    -g3")
set(CMAKE_CXX_FLAGS_RELEASE "-Ofast -g0")

#---------------------------------------------------------------------------------------------------------------------------------------------------------------
# Define the primary firmware target

# Our firmware object (ELF file)
add_executable(${CMAKE_PROJECT_NAME})

# Add STM32CubeMX generated sources
add_subdirectory(cmake/stm32cubemx)

set_property(TARGET ${CMAKE_PROJECT_NAME} PROPERTY CXX_STANDARD 20)
set_property(TARGET ${CMAKE_PROJECT_NAME} PROPERTY CXX_STANDARD_REQUIRED ON)

# Add HOLIBS
foreach(HOL_INC_DIR IN ITEMS "MJR_NbB/Inc" "MJR_SWO/Inc")
  if(EXISTS "${HOL_INC_DIR}")
    message(STATUS "Found include directory ${HOL_INC_DIR}.  Adding it to the project.")
    target_include_directories(${CMAKE_PROJECT_NAME} PRIVATE "${HOL_INC_DIR}")
  endif()
endforeach()

# Add RTT code
foreach(RTT_SRC_FILE IN ITEMS "RTT/RTT/SEGGER_RTT.c" "RTT/RTT/SEGGER_RTT_printf.c")
  if(EXISTS "${RTT_SRC_FILE}")
    message(STATUS "Found source file ${RTT_SRC_FILE}.  Adding it to the project.")
    target_sources(${CMAKE_PROJECT_NAME} PRIVATE "${RTT_SRC_FILE}")
  endif()
endforeach()

# Add RTT headers
foreach(RTT_INC_DIR IN ITEMS "RTT/RTT/" "RTT/Config/")
  if(EXISTS "${RTT_INC_DIR}")
    message(STATUS "Found include directory ${RTT_INC_DIR}.  Adding it to the project.")
    target_include_directories(${CMAKE_PROJECT_NAME} PRIVATE "${RTT_INC_DIR}")
  endif()
endforeach()

# Add my code
foreach(MJR_SRC_FILE IN ITEMS "Mainly/Src/mainly.c" "Mainly/Src/mainly.cpp")
  if(EXISTS "${MJR_SRC_FILE}")
    message(STATUS "Found source file ${MJR_SRC_FILE}.  Adding it to the project.")
    target_sources(${CMAKE_PROJECT_NAME} PRIVATE "${MJR_SRC_FILE}")
  endif()
endforeach()

# Add my header(s)
foreach(MJR_INC_DIR IN ITEMS "Mainly/Inc/")
  if(EXISTS "${MJR_INC_DIR}")
    message(STATUS "Found include directory ${MJR_INC_DIR}.  Adding it to the project.")
    target_include_directories(${CMAKE_PROJECT_NAME} PRIVATE "${MJR_INC_DIR}")
  endif()
endforeach()

# Add define for debug.
if(CMAKE_BUILD_TYPE STREQUAL "Debug")
    target_compile_definitions(${CMAKE_PROJECT_NAME} PRIVATE O_DEBUG=1)
else()
    target_compile_definitions(${CMAKE_PROJECT_NAME} PRIVATE O_DEBUG=0)
endif()

# Remove wrong libob.a library dependency when using cpp files
list(REMOVE_ITEM CMAKE_C_IMPLICIT_LINK_LIBRARIES ob)

# Add stm32cubemx to linked libraries.
target_link_libraries(${CMAKE_PROJECT_NAME} stm32cubemx)

#---------------------------------------------------------------------------------------------------------------------------------------------------------------
# Load tool configuration variables

include(tool_config.cmake)

# Potentially Used by:
#  - J-Link GDB Server SWO configuration.  
math(EXPR SERIAL_WIRE_OUTPUT_SPEED_HZ "${CPU_SPEED_HZ}/${SERIAL_WIRE_OUTPUT_PRESCALER}")

# Potentially Used by:
#  - J-Link programmer.  
#  - STM Cube Programmer (freq= component of --connect option)
math(EXPR CPU_SPEED_KHZ "${CPU_SPEED_HZ}/1000")

# Potentially Used by:
#  - STM Cube Programmer (freq= component of -swv option)
#  - Ozone debugger configuration file (SWO, TIF)
math(EXPR CPU_SPEED_MHZ "${CPU_SPEED_HZ}/1000000")

# Used by:
#  - J-Link RTT Viewer
# Potentially Used by:
#  - J-Link GDB Server 
math(EXPR SERIAL_WIRE_DEBUG_SPEED_KHZ "${SERIAL_WIRE_DEBUG_SPEED_HZ}/1000")

message(STATUS "Tool Configuration Options:")
message(STATUS "EVM_BOARD ........................ ${EVM_BOARD}")
message(STATUS "STM_DEVICE ....................... ${STM_DEVICE}")
message(STATUS "SEGGER_DEVICE .................... ${SEGGER_DEVICE}")
message(STATUS "SERIAL_WIRE_DEBUG_SPEED_HZ ....... ${SERIAL_WIRE_DEBUG_SPEED_HZ}")
message(STATUS "SERIAL_WIRE_DEBUG_SPEED_KHZ (*) .. ${SERIAL_WIRE_DEBUG_SPEED_KHZ}")
message(STATUS "CPU_SPEED_HZ ..................... ${CPU_SPEED_HZ}")
message(STATUS "CPU_SPEED_KHZ (*) ................ ${CPU_SPEED_KHZ}")
message(STATUS "CPU_SPEED_MHZ (*) ................ ${CPU_SPEED_MHZ}")
message(STATUS "SERIAL_WIRE_OUTPUT_PRESCALER ..... ${SERIAL_WIRE_OUTPUT_PRESCALER}")
message(STATUS "SERIAL_WIRE_OUTPUT_SPEED_HZ (*) .. ${SERIAL_WIRE_OUTPUT_SPEED_HZ}")
message(STATUS "Note: An (*) above indicates the value is Computed From Other Tool Configuration Options.")

#---------------------------------------------------------------------------------------------------------------------------------------------------------------
# Setup GDB file for j-link swo

# Figure out address of DBGMCU_BASE.  This test is not very robust!!  I only use a few devices: stm32f407, stm32f429, stm32g431, stm32g491, stm32l432, &
# stm32h753.  All of these devices use 0xE0042000 except for the H7 which uses 0x5C001000.  So all I have to do is look for h7, and things work out for me and
# my limited set of devices.
string(TOUPPER "${STM_DEVICE}" TMP)
if(TMP MATCHES "^STM32H7.*")  
  set(MCU_ADDR_DBGMCU_BASE "0x5C001000")
else()
  set(MCU_ADDR_DBGMCU_BASE "0xE0042000")
endif()
message(STATUS "Setting MCU_ADDR_DBGMCU_BASE to ${MCU_ADDR_DBGMCU_BASE}")

CONFIGURE_FILE(${CMAKE_SOURCE_DIR}/swo-go-jlink-gdb-server.gdb.cmake ${CMAKE_BINARY_DIR}/swo-go-jlink-gdb-server.gdb)

CONFIGURE_FILE(${CMAKE_SOURCE_DIR}/swo-go-stlink-gdb-server.gdb.cmake ${CMAKE_BINARY_DIR}/swo-go-stlink-gdb-server.gdb)

CONFIGURE_FILE(${CMAKE_SOURCE_DIR}/run-jlink-swv.sh.cmake ${CMAKE_BINARY_DIR}/run-jlink-swv.sh)

CONFIGURE_FILE(${CMAKE_SOURCE_DIR}/run-jlink-rttv.sh.cmake ${CMAKE_BINARY_DIR}/run-jlink-rttv.sh)

CONFIGURE_FILE(${CMAKE_SOURCE_DIR}/stlink-gdb-server-options.txt.cmake ${CMAKE_BINARY_DIR}/stlink-gdb-server-options.txt)

if(EXISTS "${CMAKE_SOURCE_DIR}/jlink-gdb-server-options.txt.cmake")
  CONFIGURE_FILE(${CMAKE_SOURCE_DIR}/jlink-gdb-server-options.txt.cmake ${CMAKE_BINARY_DIR}/jlink-gdb-server-options.txt)
else()
  message(WARNING "No J-Link GDB Server support without jlink-gdb-server-options.txt.cmake!")
endif()

#---------------------------------------------------------------------------------------------------------------------------------------------------------------
# Program board via ST-Link
#
# Search for programmer on the PATH for windows platforms
find_program(STM32_STLINK_PROG_BIN 
  "STM32_Programmer_CLI.exe"
  PATHS "C:/Program Files/STMicroelectronics/STM32Cube/STM32CubeProgrammer/bin/")
#
# Search for programmer on the PATH for MacOS & linux platforms
find_program(STM32_STLINK_PROG_BIN 
  "STM32_Programmer_CLI"
  PATHS "/opt/ST/STM32Cube/STM32CubeProgrammer"
        "/opt/ST/STM32CubeProgrammer"
        "~/ST/STM32Cube/STM32CubeProgrammer"
        "~/ST/STM32CubeProgrammer"
        "/Applications/STMicroelectronics/STM32Cube/STM32CubeProgrammer/STM32CubeProgrammer.app/Contents/MacOs/bin")
#
# Search for the programmer via the cube wrapper
if(NOT (EXISTS "${STM32_STLINK_PROG_BIN}"))
  message(STATUS "ST-Link Programmer binary was not found on PATH.  Searching for cube bundle manager!")
  execute_process(
    COMMAND cube "--resolve" "programmer"
    OUTPUT_VARIABLE TMP_STRING
    OUTPUT_STRIP_TRAILING_WHITESPACE
  )
  string(REGEX REPLACE "^Command: '" "" TMP_STRING "${TMP_STRING}")
  string(REGEX REPLACE "'.*$" "" TMP_STRING "${TMP_STRING}")
  set(STM32_STLINK_PROG_BIN "${TMP_STRING}")
endif()
#
# Report Results & Create program target if we can.
if(EXISTS "${STM32_STLINK_PROG_BIN}")
  message(STATUS "Found ST-Link Programmer binary: ${STM32_STLINK_PROG_BIN}")
  add_custom_target(program-stlink
    COMMAND ${STM32_STLINK_PROG_BIN} -c port=SWD -w ${PROJECT_NAME}.elf -v -rst
    DEPENDS ${PROJECT_NAME}.elf
    COMMENT "Programming device with ST-Link."
  )
  message(STATUS "'program-stlink' target created.")
else()
  message(STATUS "Unable to find STM32 Programmer binary!")
  message(WARNING "No 'program' target will be created.")
endif()

#---------------------------------------------------------------------------------------------------------------------------------------------------------------
# Create program target for J-Link
#
# Search for programmer on the PATH for windows platforms
find_program(STM32_JLINK_PROG_BIN 
  "JLink.exe"
  PATHS "C:/Program Files/SEGGER/JLink"
        "C:/Program Files (x86)/JLink"
        "$ENV{ProgramFiles}/SEGGER/JLink*"
        "$ENV{UserProfile}/SEGGER/JLink*")
# Search for programmer on the PATH for linux platforms
find_program(STM32_JLINK_PROG_BIN 
  "JLinkExe"
  PATHS "/opt/SEGGER/JLink/"
        "/opt/JLink/"
        "$ENV{HOME}/SEGGER/JLink"
        "$ENV{HOME}/opt/SEGGER/JLink"
        "$ENV{HOME}/JLink"
        "$ENV{HOME}/local/SEGGER/JLink")
# Look for versioned J-Link on Windows
if( NOT(STM32_JLINK_PROG_BIN))
  message(STATUS "J-Link binary was not found on PATH.  Searching for versioned installs!")
  file(GLOB JLINK_ALL_VER 
    "C:/Program Files/SEGGER/JLink_V*"
    "C:/Program Files(x86)/SEGGER/JLink_V*"
    "$ENV{ProgramFiles}/SEGGER/JLink_V*"
    "$ENV{UserProfile}/SEGGER/JLink_V*")
  #
  # Find the newest version of J-Link installed
  if(JLINK_ALL_VER)
    list(SORT JLINK_ALL_VER)
    list(GET JLINK_ALL_VER -1 JLINK_NEW_VER)
    set(STM32_JLINK_PROG_BIN ${JLINK_NEW_VER}/JLink.exe)
  else()
    message(STATUS "No SEGGER J-Link Install Found!")
  endif()
endif()
# Figure out SERIAL_WIRE_DEBUG_SPEED_KHZ for program.jlink.cmake
if(SERIAL_WIRE_DEBUG_SPEED_HZ)
  math(EXPR SERIAL_WIRE_DEBUG_SPEED_KHZ "${SERIAL_WIRE_DEBUG_SPEED_HZ}/1000")
else()
  math(EXPR SERIAL_WIRE_DEBUG_SPEED_KHZ "4000")
endif()
#
# Report Results & Create program target if we can.
if(EXISTS "${STM32_JLINK_PROG_BIN}")
  message(STATUS "Found J-Link binary: ${STM32_JLINK_PROG_BIN}")
  CONFIGURE_FILE(${CMAKE_SOURCE_DIR}/program.jlink.cmake ${CMAKE_BINARY_DIR}/program.jlink)
  add_custom_target(program-jlink
    COMMAND ${STM32_JLINK_PROG_BIN} -NoGui 1 -CommandFile program.jlink 
    DEPENDS ${PROJECT_NAME}.elf
    COMMENT "Programming device with J-Link."
  )
  message(STATUS "'program-jlink' target created.")
else()
  message(STATUS "Unable to find J-Link binary!")
  message(WARNING "No 'program' target will be created.")
endif()

